diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=akashhartler
user.email=akash@digialpha.co
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
credential.https://gitlab.com.provider=generic
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@github.com:HelloChapter/hellochapter-client-portal.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.develop.remote=origin
branch.develop.merge=refs/heads/develop
branch.developdoc.remote=origin
branch.developdoc.merge=refs/heads/developdoc
branch.develop_doc_upload.remote=origin
branch.develop_doc_upload.merge=refs/heads/develop_doc_upload
branch.develop_materialselection.remote=origin
branch.develop_materialselection.merge=refs/heads/develop_materialselection
branch.messages.remote=origin
branch.messages.merge=refs/heads/messages
branch.material-selection-integration.remote=origin
branch.material-selection-integration.merge=refs/heads/material-selection-integration
branch.material-selection-integration-dummydata.remote=origin
branch.material-selection-integration-dummydata.merge=refs/heads/material-selection-integration-dummydata
user.name=senthil
user.email=connect2msk@gmail.com
